services:
  db:
    container_name: db
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  myadmin:
    container_name: myadmin
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    # env_file:
    #   - ./backend/.env
    environment:
      DATABASE_HOST: db

  front:
    build:
      context: front
      dockerfile: Dockerfile
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 80:80
    env_file:
      - ./front/.env
    volumes:
      - ./front:/app
    depends_on:
      - backend

volumes:
  db:
  portainer:
