services:
  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306

  myadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: php -S 0.0.0.0:80 -t public
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    env_file:
      - ./backend/.env
    environment:
      PORT: 8000
      DATABASE_HOST: "database:3307"
      DATABASE_NAME: agence
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  front:
    build:
      context: front
      dockerfile: Dockerfile
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 3000:80
    env_file:
      - ./front/.env
    volumes:
      - ./front:/app
    depends_on:
      - backend

volumes:
  database:
  portainer:
